version: '3'

services: 
    app: 
      build: . 
      depends_on: 
        - postgres
      ports:
        - '8000:8000'
      volumes: 
        - .:/app/
        - /app/node_modules
      networks:
        - app_api
        - postgres_api
    postgres:
      image: postgres:16
      ports:
        - '5432:5432'
      volumes:
        - ./postgres:/var/lib/postgresql/data
      environment: 
        - .env
      networks:
        - postgres_api
networks:
  postgres_api:
  app_api: