require("core-js/stable");
require("regenerator-runtime/runtime");
require("./Etnia");
require("./Lingua");
require("./Palavra");
require("./Familia");
require("./Localidade");
require("./Dialeto");
require("./Idioma");
